import { GraduationCap, Briefcase, CheckCircle2 } from 'lucide-react'
import type { PersonnelStat, Personnel } from '../../types/Personnel'

export const personnelStats: PersonnelStat[] = [
  {
    code: 'MODULE_01',
    label: 'Total Guru',
    value: '86',
    icon: GraduationCap,
    trend: '86 Guru Terdaftar',
    highlighted: true,
  },
  {
    code: 'MODULE_02',
    label: 'Total Staf',
    value: '34',
    icon: Briefcase,
    trend: '34 Staf Terdaftar',
    highlighted: true,
  },
  {
    code: 'MODULE_03',
    label: 'Guru Aktif',
    value: '81',
    icon: CheckCircle2,
    highlighted: true,
    topBadge: 'Aktif',
    secondary: { value: '94.2%', label: 'Tingkat Keaktifan' },
    note: 'Presensi OK',
  },
  {
    code: 'MODULE_04',
    label: 'Staf Aktif',
    value: '32',
    icon: Briefcase,
    trend: 'Operasional Kampus',
    note: '94.1% Aktif',
    highlighted: true,
  },
]

export const personnelList: Personnel[] = [
  {
    nip: '198905122015012002',
    name: 'Ahmad Fauzan, S.Kom.',
    email: 'ahmad.fauzan@genius.sch.id',
    initials: 'AF',
    avatarTone: 'orange',
    type: 'guru',
    role: 'Informatika',
    assignment: '11 PPLG 1, 11 PPLG 2',
    homeroom: { isHomeroom: true, className: '11 PPLG 1' },
    status: 'aktif',
  },
  {
    nip: '199104182016022003',
    name: 'Siti Rahma, S.Pd.',
    email: 'siti.rahma@genius.sch.id',
    initials: 'SR',
    avatarTone: 'red',
    type: 'guru',
    role: 'Bahasa Indonesia',
    assignment: 'Kelas 10 & 11 IPS',
    homeroom: { isHomeroom: false },
    status: 'aktif',
  },
  {
    nip: '198703152014031001',
    name: 'Budi Santoso',
    email: 'budi.santoso@genius.sch.id',
    initials: 'BS',
    avatarTone: 'blue',
    type: 'staf',
    role: 'Tata Usaha',
    assignment: 'Koordinator Kepegawaian',
    homeroom: { isHomeroom: false },
    status: 'aktif',
  },
  {
    nip: '199208102018012004',
    name: 'Rina Wijaya',
    email: 'rina.wijaya@genius.sch.id',
    initials: 'RW',
    avatarTone: 'pink',
    type: 'staf',
    role: 'Administrasi',
    assignment: 'Akademik & Kearsipan',
    homeroom: { isHomeroom: false },
    status: 'aktif',
  },
  {
    nip: '198502142018011003',
    name: 'Hendra Wijaya, M.T.',
    email: 'hendra.w@genius.sch.id',
    initials: 'HW',
    avatarTone: 'orange',
    type: 'guru',
    role: 'Rekayasa Perangkat Lunak',
    assignment: 'Produktif Kejuruan',
    homeroom: { isHomeroom: true, className: '12 PPLG 2' },
    status: 'aktif',
  },
  {
    nip: '199401202020122008',
    name: 'Dewi Anggraini, S.Si.',
    email: 'dewi.anggraini@genius.sch.id',
    initials: 'DA',
    avatarTone: 'blue',
    type: 'guru',
    role: 'Fisika & Sains',
    assignment: 'Kelas 10 PPLG & MPLB',
    homeroom: { isHomeroom: false },
    status: 'aktif',
  },
  {
    nip: '198811052012011005',
    name: 'Fajar Nugraha',
    email: 'fajar.nugraha@genius.sch.id',
    initials: 'FN',
    avatarTone: 'purple',
    type: 'staf',
    role: 'Teknisi & Laboran',
    assignment: 'Lab Komputer & Jaringan',
    homeroom: { isHomeroom: false },
    status: 'nonaktif',
  },
  {
    nip: '199903122017082006',
    name: 'Maya Rizki, S.Pd.',
    email: 'maya.rizki@genius.sch.id',
    initials: 'MR',
    avatarTone: 'orange',
    type: 'guru',
    role: 'Matematika Peminatan',
    assignment: 'Kelas 10 & 12 PPLG',
    homeroom: { isHomeroom: true, className: '10 PPLG 1' },
    status: 'aktif',
  },
]