import { ClipboardList, CheckCircle2, Clock, Archive } from 'lucide-react'
import type { Task, TaskStatus } from '../types/task'
import type { StatCard } from '../types/Dashboard'

export const taskStatusLabel: Record<TaskStatus, string> = {
  draft: 'Draft',
  aktif: 'Aktif',
  selesai: 'Selesai',
  terlambat: 'Terlambat',
  diarsipkan: 'Diarsipkan',
}

export const taskStatusTone: Record<TaskStatus, string> = {
  draft: 'bg-brand-bg text-brand-navy/60',
  aktif: 'bg-status-success-bg text-status-success',
  selesai: 'bg-blue-50 text-blue-600',
  terlambat: 'bg-status-danger-bg text-status-danger',
  diarsipkan: 'bg-purple-50 text-purple-600',
}

export const taskSummary = {
  total: 128,
  active: 86,
  nearDeadline: 24,
  done: 42,
}

export const taskStatsCards: StatCard[] = [
  {
    code: 'DATA_01',
    label: 'Total Tugas',
    value: String(taskSummary.total),
    trend: 'Seluruh tugas',
    trendTone: 'neutral',
    icon: ClipboardList,
  },
  {
    code: 'DATA_02',
    label: 'Tugas Aktif',
    value: String(taskSummary.active),
    trend: 'Tugas sedang berlangsung',
    trendTone: 'neutral',
    icon: CheckCircle2,
    highlighted: true,
    badge: 'Aktif',
  },
  {
    code: 'DATA_03',
    label: 'Mendekati Deadline',
    value: String(taskSummary.nearDeadline),
    trend: 'Deadline \u2264 3 hari',
    trendTone: 'neutral',
    icon: Clock,
  },
  {
    code: 'DATA_04',
    label: 'Selesai',
    value: String(taskSummary.done),
    trend: 'Tugas telah selesai',
    trendTone: 'neutral',
    icon: Archive,
  },
]

const now = Date.now()
const day = 24 * 60 * 60 * 1000

export const taskList: Task[] = [
  {
    id: 'task-01',
    title: 'Praktik Dasar HTML',
    shortDescription: 'Latihan membuat struktur HTML dasar.',
    description:
      'Siswa membuat halaman web sederhana menggunakan tag HTML dasar (heading, paragraf, list, dan tabel).',
    teacher: 'Ahmad Fauzan, S.Kom.',
    teacherEmail: 'ahmad.fauzan@genius.sch.id',
    subject: 'Informatika',
    subjectCode: 'INF',
    classNames: ['11 PPLG 1'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 12 * day).toISOString(),
    startDate: new Date(now - 10 * day).toISOString(),
    deadline: new Date(now + 2 * day).toISOString(),
    status: 'aktif',
    submissionTotal: 32,
    submissionSubmitted: 28,
    submissionLate: 2,
    attachments: [
      { name: 'panduan-praktik-html.pdf', type: 'PDF', size: '1.2 MB' },
      { name: 'template-project.zip', type: 'ZIP', size: '3.4 MB' },
    ],
  },
  {
    id: 'task-02',
    title: 'Latihan Soal Turunan Fungsi',
    shortDescription: 'Mengerjakan 15 soal latihan turunan fungsi aljabar.',
    description: 'Mengerjakan 15 soal latihan turunan fungsi aljabar pada modul bab 3.',
    teacher: 'Maya Rizki, S.Pd.',
    teacherEmail: 'maya.rizki@genius.sch.id',
    subject: 'Matematika',
    subjectCode: 'MTK',
    classNames: ['12 PPLG 1'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 15 * day).toISOString(),
    startDate: new Date(now - 14 * day).toISOString(),
    deadline: new Date(now - 5 * day).toISOString(),
    status: 'terlambat',
    submissionTotal: 30,
    submissionSubmitted: 19,
    submissionLate: 6,
    attachments: [{ name: 'lembar-kerja-turunan.pdf', type: 'PDF', size: '820 KB' }],
  },
  {
    id: 'task-03',
    title: 'Analisis Teks Eksposisi',
    shortDescription: 'Menganalisis struktur dan kaidah kebahasaan teks eksposisi.',
    description:
      'Menganalisis struktur dan kaidah kebahasaan teks eksposisi yang telah dibagikan.',
    teacher: 'Siti Rahma, S.Pd.',
    teacherEmail: 'siti.rahma@genius.sch.id',
    subject: 'Bahasa Indonesia',
    subjectCode: 'BIN',
    classNames: ['10 IPS', '11 IPS'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 8 * day).toISOString(),
    startDate: new Date(now - 6 * day).toISOString(),
    deadline: new Date(now + 1 * day).toISOString(),
    status: 'aktif',
    submissionTotal: 28,
    submissionSubmitted: 10,
    submissionLate: 0,
    attachments: [{ name: 'teks-eksposisi-contoh.docx', type: 'DOCX', size: '340 KB' }],
  },
  {
    id: 'task-04',
    title: 'Rancangan Basis Data Perpustakaan',
    shortDescription: 'Membuat ERD dan skema basis data sederhana.',
    description:
      'Membuat ERD dan skema basis data sederhana untuk sistem perpustakaan sekolah.',
    teacher: 'Hendra Wijaya, M.T.',
    teacherEmail: 'hendra.w@genius.sch.id',
    subject: 'Rekayasa Perangkat Lunak',
    subjectCode: 'RPL',
    classNames: ['12 PPLG 2'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 20 * day).toISOString(),
    startDate: new Date(now - 18 * day).toISOString(),
    deadline: new Date(now + 3 * day).toISOString(),
    status: 'aktif',
    submissionTotal: 26,
    submissionSubmitted: 24,
    submissionLate: 1,
    attachments: [
      { name: 'template-erd.pdf', type: 'PDF', size: '540 KB' },
      { name: 'contoh-skema-db.png', type: 'PNG', size: '210 KB' },
    ],
  },
  {
    id: 'task-05',
    title: 'Laporan Praktikum Gerak Lurus',
    shortDescription: 'Menyusun laporan hasil praktikum gerak lurus.',
    description: 'Menyusun laporan hasil praktikum gerak lurus beraturan di laboratorium fisika.',
    teacher: 'Dewi Anggraini, S.Si.',
    teacherEmail: 'dewi.anggraini@genius.sch.id',
    subject: 'Fisika & Sains',
    subjectCode: 'FIS',
    classNames: ['10 MPLB'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 25 * day).toISOString(),
    startDate: new Date(now - 24 * day).toISOString(),
    deadline: new Date(now - 15 * day).toISOString(),
    status: 'selesai',
    submissionTotal: 24,
    submissionSubmitted: 24,
    submissionLate: 3,
    attachments: [{ name: 'format-laporan-praktikum.pdf', type: 'PDF', size: '410 KB' }],
  },
  {
    id: 'task-06',
    title: 'Analytical Exposition Draft',
    shortDescription: 'Menulis draf analytical exposition text.',
    description: 'Menulis draf analytical exposition text dengan topik bebas terkait isu lingkungan.',
    teacher: 'Rina Wijaya',
    teacherEmail: 'rina.wijaya@genius.sch.id',
    subject: 'Bahasa Inggris',
    subjectCode: 'ENG',
    classNames: ['11 IPS'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 2 * day).toISOString(),
    startDate: new Date(now + 1 * day).toISOString(),
    deadline: new Date(now + 9 * day).toISOString(),
    status: 'draft',
    submissionTotal: 0,
    submissionSubmitted: 0,
    submissionLate: 0,
    attachments: [],
  },
  {
    id: 'task-07',
    title: 'Quiz Harian Struktur Data',
    shortDescription: 'Quiz singkat mengenai array, linked list, dan stack.',
    description: 'Quiz singkat mengenai konsep array, linked list, dan stack.',
    teacher: 'Ahmad Fauzan, S.Kom.',
    teacherEmail: 'ahmad.fauzan@genius.sch.id',
    subject: 'Informatika',
    subjectCode: 'INF',
    classNames: ['11 PPLG 2'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 10 * day).toISOString(),
    startDate: new Date(now - 9 * day).toISOString(),
    deadline: new Date(now - 3 * day).toISOString(),
    status: 'terlambat',
    submissionTotal: 30,
    submissionSubmitted: 21,
    submissionLate: 5,
    attachments: [],
  },
  {
    id: 'task-08',
    title: 'Portofolio Karya Seni Rupa Lokal',
    shortDescription: 'Dokumentasi karya seni rupa bertema budaya lokal.',
    description:
      'Mengumpulkan dokumentasi karya seni rupa bertema budaya lokal daerah masing-masing.',
    teacher: 'Budi Santoso',
    teacherEmail: 'budi.santoso@genius.sch.id',
    subject: 'Seni Budaya Lokal',
    subjectCode: 'MLK',
    classNames: ['10 IPS'],
    academicYear: '2026/2027',
    createdDate: new Date(now - 40 * day).toISOString(),
    startDate: new Date(now - 38 * day).toISOString(),
    deadline: new Date(now - 30 * day).toISOString(),
    status: 'diarsipkan',
    submissionTotal: 28,
    submissionSubmitted: 25,
    submissionLate: 0,
    attachments: [{ name: 'ketentuan-portofolio.pdf', type: 'PDF', size: '280 KB' }],
  },
]